add_newline = false

# [localip]
# ssh_only = false
# format = "@ [$localipv4](bold red) "
# disabled = false

[character]
success_symbol = "ğŸ¦„ "
error_symbol = "ğŸ¥º "

[git_branch]
symbol = "ğŸ˜¸ "

[git_status]
style = "bold white"
conflicted = " ğŸ³"
ahead = " ğŸğŸ’¨ "
behind =" ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·â€ "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " ğŸ‘… "
deleted = " ğŸ—‘ "
